name: Package Publish


on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - name: install node_modules
        run: npm ci
      - name: Build npm
        run: npm run build
      - name: publish
        run: npm publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.npm_token }}