name: DEVELOPMENT PULL-REQUEST

on:
  pull_request:
    branches: 
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install node_modules
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: prettier
        run: npm run prettier
      - name: Test
        run: npm run test
      - name: Build npm
        run: npm run build